# Generated by Django 4.2.2 on 2023-06-29 17:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_teacher",
            field=models.BooleanField(
                default=False, help_text="", verbose_name="Is teacher"
            ),
        ),
    ]
