# Generated by Django 4.2.2 on 2023-07-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_is_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_teacher",
            field=models.BooleanField(
                default=False, help_text="Is user is teacher", verbose_name="Is teacher"
            ),
        ),
    ]
