# Generated by Django 4.2.2 on 2023-07-07 06:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_addition_id_alter_course_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="addition",
            name="title",
            field=models.CharField(default="Test title", max_length=100),
            preserve_default=False,
        ),
    ]
